### PR TITLE
Use HTTP Basic Auth and Personal Access Token.

### LINKED ISSUE #3: Plain text passwords are not good
Can we use the keyring instead?

### PR DESCRIPTION
**Pull request by david-takacs-prezi-com**
This fixes https://github.com/akoskaaa/gisty/issues/3

### CODE REVIEW

**Comment by akoshochrein** [comment]
This would make it harder to upload gists for people who don't have their passwords nor their access token set in the .gitconfig file. It would be a good idea to prompt for the pass if the token is empty. WDYT?

**Comment by akoshochrein** [comment]
As discussed, let's have the docs say that the access token should be generated and added to the global gitconf and we are good!

**Comment by david-takacs-prezi-com** [comment]
...like this?
https://github.com/david-takacs-prezi-com/gisty/tree/token-auth

On Mon, May 18, 2015 at 4:45 PM, Akos Zsolt Hochrein <
notifications@github.com> wrote:

> As discussed, let's have the docs say that the access token should be
> generated and added to the global gitconf and we are good!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akoskaaa/gisty/pull/10#issuecomment-103083522.

## 

David Takacs
Software Engineer at Prezi

**Comment by akoshochrein** [comment]
:heart: :+1: :dog:

**Pull request merged**
